apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        app: crm-frontend
    spec:
      containers:
        - name: crm-frontend
          image: IMAGE_FRONTEND
          ports:
            - containerPort: 3000
          env:
            - name: VITE_BASE_API_URL
              value: "http://crm-backend-service:8080"

