name: CRM Docker Deployment

on:
  workflow_dispatch:     # allows manual trigger
  push:
    branches:
      - main            # triggers on push to main branch

jobs:
  database:
    runs-on: self-hosted
    steps:
      - name: Create Docker network
        run: |
          if docker network ls --format '{{ .Name }}' | grep -wq crmnetwork; then
            echo "crmnetwork exists"
          else
            docker network create crmnetwork
          fi

      - name: Setup MySQL
        run: |
          # Remove existing container if it exists
          if docker ps -a --format '{{.Names}}' | grep -wq crmdb; then
            echo "crmdb already exists, removing old container"
            docker rm -f crmdb
          fi

          # Run MySQL container
          docker run -d --name crmdb \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e MYSQL_DATABASE=crm \
            -p 3306:3306 \
            --network crmnetwork \
            mysql:8

  build:
    needs: database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend Docker image
      - name: Build backend image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/crm-api:latest ./crm-api

      # Build Frontend Docker image
      - name: Build frontend image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/crm-web:latest ./crm-web

      # Push Backend Docker image
      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/crm-api:latest

      # Push Frontend Docker image
      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/crm-web:latest
